### PR TITLE
Pcplod

### LINKED ISSUE #40: Consider using pcplod for testing
As per a conversation with @fommil in `typelevel/general`, consider adding some tests with this [pcplod](https://github.com/ensime/pcplod). If we did this, we'd want to add a new submodule (e.g. testing) that would be unpublished and would run the tests.

Benefits:
1. We'd be verifying that the presentation compiler works with _kind-projector_.
2. Provides another method of ensuring the transformations happen as expected.
3. Policy of only adding rewrites that work in the presentation compiler.

Drawbacks:
1. Adding dependencies on both pcplod and a testing framework.
2. Blocks kind-projector progress based on presentation compiler status.

Overall I think it's worth exploring. Worst-case we set these tests up and later decide to disable them. Since kind-projector runs so early I think it's unlikely that we'd become majorly blocked on PC issues (but you never know).

### PR DESCRIPTION
**Pull request by fommil**
close #40 and fix a minor problem in your build.

upcoming is to add @yilinwei's failing example https://gist.github.com/yilinwei/0c78c6de7ed62741f15385439e23196d

### CODE REVIEW

**Comment by fommil** [comment]
ok, this is good to go. @non to give you (and me) some piece of mind. Also, note that type-at-point doesn't like the type constructors. Maybe something to improve on?

**Comment by fommil** [comment]
I also bumped your testing matrix to 2.12.1. I wouldn't bump to 2.11.9 because there are some non-forwards compatible binary changes there.

**Comment by non** [comment]
Thanks!

**Comment by non** [comment]
I'm merging this now, but feel free to open any issues around the type-at-point issues and we can try to fix those. Thanks again for improving the test situation!

**Pull request merged**
