### PR TITLE
Scala-2.13.0-M1

### PR DESCRIPTION
**Pull request by golem131**

### CODE REVIEW

**Comment by SethTisue** [comment]
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.ensime#pcplod_2.13.0-M1;1.2.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

https://github.com/ensime/pcplod/issues/22

**Comment by etorreborre** [comment]
It seems like `kind-projector` depends on `ensime` only for tests. Maybe we can still publish a version for scala `2.13.0-M1` without the corresponding tests? cc @non

**Comment by SethTisue** [comment]
pcplod has released, so this is now unblocked

**Comment by SethTisue** [comment]
can someone with the needed access hit "restart" on Travis?

**Comment by non** [comment]
Restarting...

**Comment by SethTisue** [comment]
failed — I think the pcplod version needs to be bumped from 1.2.0 to 1.2.1 for this to work

**Comment by non** [comment]
I'll test with that version locally. If it works I'll merge this PR and then push that change myself.

**Comment by non** [comment]
Merging. Thanks @golem131!

**Comment by non** [comment]
Kind-projector 0.9.4 was just released, with 2.13.0-M1 support. Should hit Maven Central in a few hours.

**Pull request merged**
