### PR TITLE
Configure TravisCI, cleanup the build & upgrade

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Travis passed on my fork: https://travis-ci.org/dwijnand/kind-projector/builds/85540551

You need to flip the switch to enable it here.

If you want to see it green here too before merging you need to close and re-open this pull request to trigger Travis.

**Comment by non** [comment]
Thanks for this! I'll look at getting this merged (and Travis turned on) later today.

**Comment by non** [comment]
Thanks! This is great, and looks like Travis passed.

**Comment by dwijnand** [comment]
Cool :)

**Pull request merged**
