### PR TITLE
Polymorphic lambdas.

### PR DESCRIPTION
**Pull request by paulp**
This is incomplete but I wanted to obtain feedback now. The tests do pass on 2.10/2.11/2.12.

### CODE REVIEW

**Comment by non** [comment]
This looks really good. Are there known deficiencies or limitations right now? Extra features you want to include?

From what I can tell it doesn't change things too much -- since *kind-projector* already forces you to reserve `Lambda` and `λ` it's not anymore restrictive than it would have been.

I'll try to do a more thorough review later tonight, including some test cases of my own. But so far this looks good to me. The one addition we definitely need is something in the README to help explain what this is, but I can help tackle that once everything else is done.

**Comment by paulp** [comment]
There are various other shenanigans which we could perform based on the type argument(s) applied at Lambda, but they all risk becoming too much magic.

For that matter it's up for debate whether the one type argument case should stay. I think it's only really usable for one case, it's just that it's a really common case.

```scala
     λ[ToSelf[Map[?, Int]]](_ mapValues (_ * 2)) // works at the moment if you have ToSelf defined
(vs) λ[Map[?, Int] ~> Map[?, Int]](_ mapValues (_ * 2))
```

I think the term Lambda is a lot more likely to collide than the type Lambda, but I also think it's an acceptable price to pay for consistency.

I'm not aware of deficiencies as yet. I'm working through the quasar codebase converting to this syntax to make sure I can't think of anything better. I defects make themselves known I'll report here.

**Comment by paulp** [comment]
I added some more tests, including one with lambda-to-lambda.
```
val tupleTakeFirst = λ[λ[A => (A, Int)] ~> List](x => List(x._1))
```

**Comment by paulp** [comment]
[Here's an ongoing look at what this pull request is allowing me to do in quasar](https://github.com/quasar-analytics/quasar/compare/master...paulp:wip/polylambda?w=1).

**Comment by paulp** [comment]
As of e4186665cc all the quasar tests are still passing, which may provide a bit of confidence beyond the included tests.

**Comment by xuwei-k** [comment]
🎉  https://github.com/xuwei-k/scalaz/commit/4d0725ea139fb2cf37e3cef28ea30f3a050860da

**Comment by non** [comment]
Given how clunky working with *natural transformations* is I think the one-type argument case is worth keeping. I agree about limiting some of the more magical future directions (although I'm open to being convinced).

I'm inclined to merge this, write some documentation for it (I'll submit a PR you can review) and then do a release. @paulp does this sound good to you?

**Comment by paulp** [comment]
@non Indeed it does!

**Pull request merged**
