### PR TITLE
Use beautiful unicode identifiers.

### PR DESCRIPTION
**Pull request by non**
This commit changes the way type lambdas are encoded.
Currently, the encoding looks like this:

`Function2[?, Int, ?]` becomes:
  `({type L_kp[X_kp0, X_kp2] = Function2[X_kp0, Int, X_kp2]})#L_kp`

With this commit, it would instead be:
  `({type Λ[α0, α2] = Function2[α0, Int, α2]})#Λ`

Benefits of this change:

1. Encoding looks better.
2. Error messages are much cleaner.
3. Closer to existing community conventions.

Drawbacks to this change:

1. Requires users to be able to display unicode.
2. Complicates using types named "Λ", "α0", etc. with kind-projector.

Overall, I think this would be a win, but I'll have to canvas opinions.

### CODE REVIEW

**Comment by non** [comment]
I think I'm going to merge this and target it for a 0.6.0 release. I'll go with @adelbertc's suggestion of `_Λ[a]` to start with.

How do people feel about @OlegYch's suggestion to use `_Λ[α, β, ...]` instead of `_Λ[α0, α1, ...]`?

**Comment by jedws** [comment]
+1 for @OlegYch's naming style.

As a possible throwaway suggestion, `$` is the usual synthetic identifier suffix, what about Λ$? eg. `Λ$[α, β, ...]`

**Comment by non** [comment]
I took @jedws' suggestion and used `Λ$` for the lambda name. I also updated the params to go `α, β, ...` -- at the 25th parameter they will cycle back around to `α1, β1, ...` and so on.

I also added a system property to use ASCII names instead of Unicode. `-Dkp:genAsciiNames=true` will use the old names (`L_kp`, `X_kp0`, etc.).

**Comment by non** [comment]
I think I'm going to merge this commit now, since it has a lot of good stuff in it.

I'll wait awhile to release 0.6.0, so feel free to open new issues with suggestions or comments (or even comment here).

**Pull request merged**
